In [18]:
import numpy as np

In [27]:
arr = np.random.normal(0, 0.1, (4, 788))

In [32]:
for data in arr:
    x_train = (data[:784] / 255.0) + 0.01
    y_train = data[784:]
    model.train(x_train, y_train)

[-0.03101776 -0.04358946  0.12203694  0.04976589]
[-0.01783929  0.0690641   0.14542006 -0.04453027]
[ 0.05054058 -0.15950309  0.0102457  -0.11115988]
[ 0.18164729 -0.10911047  0.04288194  0.014635  ]
